- name: catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: Disable old nodejs version and enable nodejs 18 version
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

 

  